#include "lang.h"
#include "storage.h"

#ifndef SIMULATOR
#include "esp_system.h"
#endif

static lang_t current_language = LANG_EN;

static const char *strings_en[STR_COUNT] = {
    [STR_LANGUAGE_EN] = "English",
    [STR_LANGUAGE_ES] = "Espanol",
    [STR_SETTING_LANGUAGE] = "Language",
    [STR_SETTING_AUTODIM_OFF] = "Auto-dim\nOFF",
    [STR_SETTING_AUTODIM_15S] = "Auto-dim\n15s",
    [STR_SETTING_AUTODIM_30S] = "Auto-dim\n30s",
    [STR_SETTING_AUTODIM_60S] = "Auto-dim\n60s",
    [STR_SETTING_COLORS_PLAYER] = "Colors\nPlayer",
    [STR_SETTING_COLORS_LIFE] = "Colors\nLife",
    [STR_SETTING_DESELECT_NEVER] = "Deselect\nNever",
    [STR_SETTING_DESELECT_5S] = "Deselect\n5s",
    [STR_SETTING_DESELECT_15S] = "Deselect\n15s",
    [STR_SETTING_DESELECT_30S] = "Deselect\n30s",
    [STR_SETTING_ORIENTATION_ABSOLUTE] = "Orientation\nAbsolute",
    [STR_SETTING_ORIENTATION_CENTRIC] = "Orientation\nCentric",
    [STR_SETTING_ORIENTATION_TABLETOP] = "Orientation\nTabletop",
    [STR_SETTING_AUTO_ELIM_ON] = "Auto\nElimination\nON",
    [STR_SETTING_AUTO_ELIM_OFF] = "Auto\nElimination\nOFF",
    [STR_SETTING_RANDOM_FIRST_ON] = "Random\nFirst\nON",
    [STR_SETTING_RANDOM_FIRST_OFF] = "Random\nFirst\nOFF",
    [STR_SETTING_MENU_FACE_PLAYER] = "Menus\nFace\nPlayer",
    [STR_SETTING_MENU_FIXED] = "Menus\nFixed",
    [STR_SETTING_MULTI_SELECT_ON] = "Multi-\nSelect\nON",
    [STR_SETTING_MULTI_SELECT_OFF] = "Multi-\nSelect\nOFF",
    [STR_SETTING_BRIGHTNESS] = "Brightness",
    [STR_SETTING_BATTERY] = "Battery",
    [STR_SETTING_TABLE_SYNC] = "Table Sync\n(Experimental)",
    [STR_SETTING_ROTATE_SCREEN] = "Rotate\nScreen",
    [STR_SETTINGS_MORE] = "More",
    [STR_TABLE_SYNC_JOINING] = "Joining...",
    [STR_TABLE_SYNC_INVITING] = "Inviting\n#%04d",
    [STR_TABLE_SYNC_IN_GAME] = "In Game\n#%04d",
    [STR_TABLE_SYNC_1P_NO_SYNC] = "1P View:\nNo Sync",
    [STR_TABLE_SYNC_RADIO_ERROR] = "Radio\nError",
    [STR_TABLE_SYNC_OFF] = "Sync Off",
    [STR_TABLE_SYNC_HOLD_INVITE] = "Hold to\nInvite",
    [STR_TABLE_SYNC_HOLD_START] = "Hold to\nStart",
    [STR_TABLE_SYNC_HOLD_JOIN] = "Hold to\nJoin",
    [STR_TABLE_SYNC_HOLD_LEAVE] = "Hold to\nLeave",
    [STR_MENU_SETTINGS] = "Settings",
    [STR_MENU_GAME_MODE] = "Game\nMode",
    [STR_MENU_TOOLS] = "Tools",
    [STR_MENU_RESET_HOLD] = "Reset\n(Hold)",
    [STR_TOOL_DICE] = "Dice",
    [STR_TOOL_TIMER] = "Timer",
    [STR_TOOL_EVENT_LOG] = "Event\nLog",
    [STR_TOOL_MANA_POOL] = "Mana\nPool",
    [STR_BRIGHTNESS_FMT] = "Brightness: %d%%",
    [STR_BRIGHTNESS_HINT] = "Turn knob for brightness",
    [STR_BATTERY_TITLE] = "Battery",
    [STR_BATTERY_UNKNOWN] = "Battery: --%",
    [STR_BATTERY_FMT] = "Battery: %d%%",
    [STR_BATTERY_NOT_CALIBRATED] = "No calibrated reading",
    [STR_BATTERY_CALIBRATED_FMT] = "%.2fV calibrated",
    [STR_ROTATE_TITLE] = "Rotate Screen",
    [STR_ROTATE_HINT] = "Turn knob to rotate",
    [STR_COLOR_GREEN] = "Green",
    [STR_COLOR_PURPLE] = "Purple",
    [STR_COLOR_BLUE] = "Blue",
    [STR_COLOR_YELLOW] = "Yellow",
    [STR_COLOR_RED] = "Red",
    [STR_COLOR_ORANGE] = "Orange",
    [STR_COLOR_CYAN] = "Cyan",
    [STR_COLOR_PINK] = "Pink",
    [STR_COLOR_LIME] = "Lime",
    [STR_COLOR_INDIGO] = "Indigo",
    [STR_COLOR_ROSE] = "Rose",
    [STR_COLOR_WHITE] = "White",
    [STR_COLOR_TEAL] = "Teal",
    [STR_COLOR_AMBER] = "Amber",
    [STR_COLOR_BROWN] = "Brown",
    [STR_COLOR_GRAY] = "Gray",
    [STR_COLOR_SAGE] = "Sage",
    [STR_COLOR_BLACK] = "Black",
    [STR_SETTING_WIFI] = "WiFi",
    [STR_SETTING_UPDATES] = "Updates",
    [STR_WIFI_TITLE] = "WiFi",
    [STR_WIFI_SSID] = "SSID",
    [STR_WIFI_PASSWORD] = "Password",
    [STR_WIFI_CONNECT] = "Connect",
    [STR_WIFI_FORGET_HOLD] = "Forget\n(Hold)",
    [STR_WIFI_NOT_CONFIGURED] = "Not configured",
    [STR_WIFI_CONNECTING] = "Connecting...",
    [STR_WIFI_DISCONNECT_FMT] = "Disconnect\n%s",
    [STR_WIFI_FAILED] = "Connection failed",
    [STR_WIFI_ENTER_SSID] = "Enter SSID",
    [STR_WIFI_ENTER_PASSWORD_FMT] = "Enter password for\n%s",
    [STR_OTA_TITLE] = "Updates",
    [STR_OTA_CURRENT_FMT] = "Current: %s",
    [STR_OTA_CHECK_NOW] = "Check for\nUpdates",
    [STR_OTA_APPLY_HOLD] = "Apply\n(Hold)",
    [STR_OTA_CHECKING] = "Checking...",
    [STR_OTA_UP_TO_DATE] = "Up to date",
    [STR_OTA_AVAILABLE_FMT] = "Update available\n%s",
    [STR_OTA_UPDATING] = "Updating...\nDo not disconnect",
    [STR_OTA_ERROR_FMT] = "Error: %s",
    [STR_OTA_NEED_WIFI] = "Connect to WiFi first",
    [STR_OTA_TAP_TO_CHECK] = "Tap to check",
    [STR_OTA_OPEN_WIFI] = "Open WiFi",
    [STR_WIFI_SCANNING] = "Scanning...",
    [STR_WIFI_TYPE_MANUALLY] = "Type manually...",
    [STR_WIFI_NO_NETWORKS] = "No networks found",
    [STR_WIFI_OPEN_SUFFIX] = " (open)",
    [STR_WIFI_STATUS_TITLE] = "Connection",
    [STR_WIFI_CONNECTING_TO_FMT] = "Connecting to\n%s...",
    [STR_WIFI_CONNECT_OK_FMT] = "Connected to %s\nIP: %s",
    [STR_WIFI_CONNECT_FAIL_FMT] = "Could not connect to\n%s",
    [STR_OK] = "OK",

    [STR_CHOOSE_PLAYER] = "Choose player",
    [STR_TAB_COMMANDER] = "Commander",
    [STR_TAB_PARTNER] = "Partner",
    [STR_PARTNER_SUFFIX] = "%s\n(Partner)",
    [STR_DAMAGE_PREFIX] = "Damage: %d",
    [STR_TURN_KNOB_THEN_APPLY] = "Turn knob, then apply",
    [STR_APPLY] = "Apply",
    [STR_TURN_FMT_SOLO] = "turn  %lu:%02lu",
    [STR_TURN_FMT_NUMBERED] = "turn %d  %lu:%02lu",
    [STR_TURN_INITIAL] = "turn  0:00",

    [STR_MENU_NAME_COLOR] = "Name/\nColor",
    [STR_MENU_COMMANDER_DAMAGE] = "Commander\nDamage",
    [STR_MENU_ALL_DAMAGE] = "All\nDamage",
    [STR_MENU_COUNTERS] = "Counters",
    [STR_UNDO_ELIMINATION_TITLE] = "Undo elimination",
    [STR_UNDO_ELIMINATION_HINT] = "Restore the action that eliminated this player",
    [STR_UNDO] = "Undo",
    [STR_ALL_PLAYERS] = "All players",
    [STR_ALL_OPPONENTS] = "All opponents",
    [STR_DAMAGE_COLON] = "Damage: %d",
    [STR_INCLUDE_MYSELF] = "Include myself",
    [STR_INCLUDE_MYSELF_NAMED] = "Include myself (%s)",
    [STR_MENU_RENAME] = "Rename",
    [STR_MENU_DEFAULT_SETTING] = "Default\nSetting",
    [STR_MENU_LIFE_COLOR] = "Life\nColor",
    [STR_MENU_CUSTOM_COLOR] = "Custom\nColor",
    [STR_COLOR_TITLE] = "%s\nColor",

    [STR_COUNTER_COMMANDER_TAX] = "Commander Tax",
    [STR_COUNTER_COMMANDER_TAX_MENU] = "Commander\nTax",
    [STR_COUNTER_PARTNER_TAX] = "Partner Tax",
    [STR_COUNTER_PARTNER_TAX_MENU] = "Partner\nTax",
    [STR_COUNTER_POISON] = "Poison",
    [STR_COUNTER_EXPERIENCE] = "Experience",

    [STR_LOG_AGO_MIN] = "%2lum ago",
    [STR_LOG_AGO_SEC] = "%2lus ago",
    [STR_LOG_CMD_DEALT] = "%s: %s dealt %d cmd to %s",
    [STR_LOG_CMD_DEALT_PARTNER] = "%s: %s dealt %d partner cmd to %s",
    [STR_LOG_COUNTER_INCREASED] = "%s: %s increased %s by %d",
    [STR_LOG_COUNTER_DECREASED] = "%s: %s decreased %s by %d",
    [STR_LOG_LIFE_GAINED] = "%s: %s gained %d life",
    [STR_LOG_LIFE_LOST] = "%s: %s lost %d life",
    [STR_LOG_EMPTY] = "No events yet",
    [STR_LOG_COUNTER_FALLBACK] = "Counter",
    [STR_LOG_TITLE] = "Event Log",
    [STR_LOG_UNDO_HOLD] = "Undo\n(Long Press)",
    [STR_LOG_PAGE_FMT] = "%d-%d of %d",

    [STR_RENAME_TYPE_NEW] = "Type new...",
    [STR_RENAME_NEW_NAME] = "New name",
    [STR_RENAME_FMT] = "Rename %s",
    [STR_RENAME_SELECT] = "Select",
    [STR_RENAME_SAVE] = "save",

    [STR_GAME_MODE_PLAYERS_FMT] = "Players\n%d",
    [STR_GAME_MODE_TRACK_FMT] = "Track\n%d",
    [STR_GAME_MODE_LIFE_FMT] = "Life\n%d",
    [STR_GAME_MODE_APPLY_HOLD] = "Apply\n(Hold)",
    [STR_GAME_MODE_LIFE_TITLE] = "Life Total",
    [STR_GAME_MODE_TURN_KNOB_ADJUST] = "Turn knob to adjust",

    [STR_DICE_HOLD_TO_REROLL] = "Hold to re-roll",

    [STR_MANA_POOL_TITLE] = "Mana Pool",
    [STR_MANA_CLEAR_ALL_HOLD] = "Clear All\n(Hold)",
};

static const char *strings_es[STR_COUNT] = {
    [STR_LANGUAGE_EN] = "Inglés",
    [STR_LANGUAGE_ES] = "Español",
    [STR_SETTING_LANGUAGE] = "Idioma",
    [STR_SETTING_AUTODIM_OFF] = "Auto-brillo\nOFF",
    [STR_SETTING_AUTODIM_15S] = "Auto-brillo\n15s",
    [STR_SETTING_AUTODIM_30S] = "Auto-brillo\n30s",
    [STR_SETTING_AUTODIM_60S] = "Auto-brillo\n60s",
    [STR_SETTING_COLORS_PLAYER] = "Colores\nJugador",
    [STR_SETTING_COLORS_LIFE] = "Colores\nVida",
    [STR_SETTING_DESELECT_NEVER] = "Deselección\nNunca",
    [STR_SETTING_DESELECT_5S] = "Deselección\n5s",
    [STR_SETTING_DESELECT_15S] = "Deselección\n15s",
    [STR_SETTING_DESELECT_30S] = "Deselección\n30s",
    [STR_SETTING_ORIENTATION_ABSOLUTE] = "Orientación\nAbsoluta",
    [STR_SETTING_ORIENTATION_CENTRIC] = "Orientación\nCéntrica",
    [STR_SETTING_ORIENTATION_TABLETOP] = "Orientación\nMesa",
    [STR_SETTING_AUTO_ELIM_ON] = "Auto\nEliminación\nON",
    [STR_SETTING_AUTO_ELIM_OFF] = "Auto\nEliminación\nOFF",
    [STR_SETTING_RANDOM_FIRST_ON] = "Primero\nAleatorio\nON",
    [STR_SETTING_RANDOM_FIRST_OFF] = "Primero\nAleatorio\nOFF",
    [STR_SETTING_MENU_FACE_PLAYER] = "Menús\nHacia\nJugador",
    [STR_SETTING_MENU_FIXED] = "Menús\nFijos",
    [STR_SETTING_MULTI_SELECT_ON] = "Multi-\nSelección\nON",
    [STR_SETTING_MULTI_SELECT_OFF] = "Multi-\nSelección\nOFF",
    [STR_SETTING_BRIGHTNESS] = "Brillo",
    [STR_SETTING_BATTERY] = "Batería",
    [STR_SETTING_TABLE_SYNC] = "Sync. Mesa\n(Experimental)",
    [STR_SETTING_ROTATE_SCREEN] = "Rotar\nPantalla",
    [STR_SETTINGS_MORE] = "Más",
    [STR_TABLE_SYNC_JOINING] = "Uniéndose...",
    [STR_TABLE_SYNC_INVITING] = "Invitando\n#%04d",
    [STR_TABLE_SYNC_IN_GAME] = "En Partida\n#%04d",
    [STR_TABLE_SYNC_1P_NO_SYNC] = "Vista 1J:\nSin Sync",
    [STR_TABLE_SYNC_RADIO_ERROR] = "Error de\nRadio",
    [STR_TABLE_SYNC_OFF] = "Sync Apagada",
    [STR_TABLE_SYNC_HOLD_INVITE] = "Mantener\npara Invitar",
    [STR_TABLE_SYNC_HOLD_START] = "Mantener\npara Iniciar",
    [STR_TABLE_SYNC_HOLD_JOIN] = "Mantener\npara Unirse",
    [STR_TABLE_SYNC_HOLD_LEAVE] = "Mantener\npara Salir",
    [STR_MENU_SETTINGS] = "Ajustes",
    [STR_MENU_GAME_MODE] = "Modo de\nJuego",
    [STR_MENU_TOOLS] = "Herramientas",
    [STR_MENU_RESET_HOLD] = "Reiniciar\n(Mantener)",
    [STR_TOOL_DICE] = "Dado",
    [STR_TOOL_TIMER] = "Temporizador",
    [STR_TOOL_EVENT_LOG] = "Registro\nde Eventos",
    [STR_TOOL_MANA_POOL] = "Reserva\nde Maná",
    [STR_BRIGHTNESS_FMT] = "Brillo: %d%%",
    [STR_BRIGHTNESS_HINT] = "Gira la rueda para el brillo",
    [STR_BATTERY_TITLE] = "Batería",
    [STR_BATTERY_UNKNOWN] = "Batería: --%",
    [STR_BATTERY_FMT] = "Batería: %d%%",
    [STR_BATTERY_NOT_CALIBRATED] = "Lectura no calibrada",
    [STR_BATTERY_CALIBRATED_FMT] = "%.2fV calibrado",
    [STR_ROTATE_TITLE] = "Rotar Pantalla",
    [STR_ROTATE_HINT] = "Gira la rueda para rotar",
    [STR_COLOR_GREEN] = "Verde",
    [STR_COLOR_PURPLE] = "Morado",
    [STR_COLOR_BLUE] = "Azul",
    [STR_COLOR_YELLOW] = "Amarillo",
    [STR_COLOR_RED] = "Rojo",
    [STR_COLOR_ORANGE] = "Naranja",
    [STR_COLOR_CYAN] = "Cian",
    [STR_COLOR_PINK] = "Rosa",
    [STR_COLOR_LIME] = "Lima",
    [STR_COLOR_INDIGO] = "Índigo",
    [STR_COLOR_ROSE] = "Rosado",
    [STR_COLOR_WHITE] = "Blanco",
    [STR_COLOR_TEAL] = "Verde Azulado",
    [STR_COLOR_AMBER] = "Ámbar",
    [STR_COLOR_BROWN] = "Marrón",
    [STR_COLOR_GRAY] = "Gris",
    [STR_COLOR_SAGE] = "Salvia",
    [STR_COLOR_BLACK] = "Negro",
    [STR_SETTING_WIFI] = "WiFi",
    [STR_SETTING_UPDATES] = "Actualizaciones",
    [STR_WIFI_TITLE] = "WiFi",
    [STR_WIFI_SSID] = "Red (SSID)",
    [STR_WIFI_PASSWORD] = "Contraseña",
    [STR_WIFI_CONNECT] = "Conectar",
    [STR_WIFI_FORGET_HOLD] = "Olvidar\n(Mantener)",
    [STR_WIFI_NOT_CONFIGURED] = "Sin configurar",
    [STR_WIFI_CONNECTING] = "Conectando...",
    [STR_WIFI_DISCONNECT_FMT] = "Desconectar\n%s",
    [STR_WIFI_FAILED] = "Fallo de conexión",
    [STR_WIFI_ENTER_SSID] = "Introduce el SSID",
    [STR_WIFI_ENTER_PASSWORD_FMT] = "Introduce la contraseña de\n%s",
    [STR_OTA_TITLE] = "Actualizaciones",
    [STR_OTA_CURRENT_FMT] = "Actual: %s",
    [STR_OTA_CHECK_NOW] = "Buscar\nActualización",
    [STR_OTA_APPLY_HOLD] = "Aplicar\n(Mantener)",
    [STR_OTA_CHECKING] = "Buscando...",
    [STR_OTA_UP_TO_DATE] = "Ya actualizado",
    [STR_OTA_AVAILABLE_FMT] = "Actualización\ndisponible %s",
    [STR_OTA_UPDATING] = "Actualizando...\nNo desconectes",
    [STR_OTA_ERROR_FMT] = "Error: %s",
    [STR_OTA_NEED_WIFI] = "Conecta al WiFi primero",
    [STR_OTA_TAP_TO_CHECK] = "Toca para buscar",
    [STR_OTA_OPEN_WIFI] = "Abrir WiFi",
    [STR_WIFI_SCANNING] = "Escaneando...",
    [STR_WIFI_TYPE_MANUALLY] = "Escribir manualmente...",
    [STR_WIFI_NO_NETWORKS] = "No se encontraron redes",
    [STR_WIFI_OPEN_SUFFIX] = " (abierta)",
    [STR_WIFI_STATUS_TITLE] = "Conexión",
    [STR_WIFI_CONNECTING_TO_FMT] = "Conectando a\n%s...",
    [STR_WIFI_CONNECT_OK_FMT] = "Conectado a %s\nIP: %s",
    [STR_WIFI_CONNECT_FAIL_FMT] = "No se pudo conectar a\n%s",
    [STR_OK] = "Aceptar",

    [STR_CHOOSE_PLAYER] = "Elige jugador",
    [STR_TAB_COMMANDER] = "Comandante",
    [STR_TAB_PARTNER] = "Compañero",
    [STR_PARTNER_SUFFIX] = "%s\n(Compañero)",
    [STR_DAMAGE_PREFIX] = "Daño: %d",
    [STR_TURN_KNOB_THEN_APPLY] = "Gira la rueda y aplica",
    [STR_APPLY] = "Aplicar",
    [STR_TURN_FMT_SOLO] = "turno  %lu:%02lu",
    [STR_TURN_FMT_NUMBERED] = "turno %d  %lu:%02lu",
    [STR_TURN_INITIAL] = "turno  0:00",

    [STR_MENU_NAME_COLOR] = "Nombre/\nColor",
    [STR_MENU_COMMANDER_DAMAGE] = "Daño de\nComandante",
    [STR_MENU_ALL_DAMAGE] = "Daño a\nTodos",
    [STR_MENU_COUNTERS] = "Contadores",
    [STR_UNDO_ELIMINATION_TITLE] = "Deshacer eliminación",
    [STR_UNDO_ELIMINATION_HINT] = "Restaura la acción que eliminó a este jugador",
    [STR_UNDO] = "Deshacer",
    [STR_ALL_PLAYERS] = "Todos los jugadores",
    [STR_ALL_OPPONENTS] = "Todos los rivales",
    [STR_DAMAGE_COLON] = "Daño: %d",
    [STR_INCLUDE_MYSELF] = "Incluirme",
    [STR_INCLUDE_MYSELF_NAMED] = "Incluirme (%s)",
    [STR_MENU_RENAME] = "Renombrar",
    [STR_MENU_DEFAULT_SETTING] = "Ajuste\npor Defecto",
    [STR_MENU_LIFE_COLOR] = "Color\nsegún Vida",
    [STR_MENU_CUSTOM_COLOR] = "Color\nPersonalizado",
    [STR_COLOR_TITLE] = "%s\nColor",

    [STR_COUNTER_COMMANDER_TAX] = "Impuesto de Comandante",
    [STR_COUNTER_COMMANDER_TAX_MENU] = "Impuesto\nComandante",
    [STR_COUNTER_PARTNER_TAX] = "Impuesto de Compañero",
    [STR_COUNTER_PARTNER_TAX_MENU] = "Impuesto\nCompañero",
    [STR_COUNTER_POISON] = "Veneno",
    [STR_COUNTER_EXPERIENCE] = "Experiencia",

    [STR_LOG_AGO_MIN] = "hace %2lum",
    [STR_LOG_AGO_SEC] = "hace %2lus",
    [STR_LOG_CMD_DEALT] = "%s: %s hizo %d de comandante a %s",
    [STR_LOG_CMD_DEALT_PARTNER] = "%s: %s hizo %d de comandante (compañero) a %s",
    [STR_LOG_COUNTER_INCREASED] = "%s: %s aumentó %s en %d",
    [STR_LOG_COUNTER_DECREASED] = "%s: %s redujo %s en %d",
    [STR_LOG_LIFE_GAINED] = "%s: %s ganó %d de vida",
    [STR_LOG_LIFE_LOST] = "%s: %s perdió %d de vida",
    [STR_LOG_EMPTY] = "Aún no hay eventos",
    [STR_LOG_COUNTER_FALLBACK] = "Contador",
    [STR_LOG_TITLE] = "Registro de Eventos",
    [STR_LOG_UNDO_HOLD] = "Deshacer\n(Mantener)",
    [STR_LOG_PAGE_FMT] = "%d-%d de %d",

    [STR_RENAME_TYPE_NEW] = "Escribir nuevo...",
    [STR_RENAME_NEW_NAME] = "Nuevo nombre",
    [STR_RENAME_FMT] = "Renombrar %s",
    [STR_RENAME_SELECT] = "Elegir",
    [STR_RENAME_SAVE] = "guardar",

    [STR_GAME_MODE_PLAYERS_FMT] = "Jugadores\n%d",
    [STR_GAME_MODE_TRACK_FMT] = "En pantalla\n%d",
    [STR_GAME_MODE_LIFE_FMT] = "Vida\n%d",
    [STR_GAME_MODE_APPLY_HOLD] = "Aplicar\n(Mantener)",
    [STR_GAME_MODE_LIFE_TITLE] = "Vida Inicial",
    [STR_GAME_MODE_TURN_KNOB_ADJUST] = "Gira la rueda para ajustar",

    [STR_DICE_HOLD_TO_REROLL] = "Mantener para volver a tirar",

    [STR_MANA_POOL_TITLE] = "Reserva de Maná",
    [STR_MANA_CLEAR_ALL_HOLD] = "Borrar Todo\n(Mantener)",
};

void lang_init(void)
{
    current_language = (nvs_get_language() != 0) ? LANG_ES : LANG_EN;
}

lang_t lang_get(void)
{
    return current_language;
}

void lang_set(lang_t lang)
{
    if (lang < 0 || lang >= LANG_COUNT) return;
    nvs_set_language(lang);
    settings_save();
#ifdef SIMULATOR
    /* The sim has no real reboot; screens are only ever built once at
       startup, same as firmware, so a language change here just won't
       relabel already-built screens. That's fine for the sim's purpose
       (screenshots/tests re-launch the process anyway). */
    current_language = lang;
#else
    esp_restart(); /* screens are only ever built once, at boot, from t() */
#endif
}

const char *t(string_id_t id)
{
    if (id < 0 || id >= STR_COUNT) return "";
    const char *s = (current_language == LANG_ES) ? strings_es[id] : strings_en[id];
    return s ? s : strings_en[id];
}
